# Generated by Django 3.2.7 on 2021-10-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
    ]
