# Generated by Django 3.2.7 on 2021-10-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region_name',
        ),
    ]
