# Generated by Django 3.2.7 on 2021-09-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='video',
            field=models.FileField(default=1, upload_to='static/videos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.lessons'),
        ),
        migrations.DeleteModel(
            name='Lesson_Structure',
        ),
    ]
