# Generated by Django 3.2.7 on 2021-09-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210910_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_structure',
            name='slug',
        ),
    ]
