# Generated by Django 3.2.7 on 2021-09-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210922_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='category',
            new_name='course',
        ),
    ]
