# Generated by Django 3.2.7 on 2021-09-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='price',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
