# Generated by Django 3.2.7 on 2021-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210923_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='status',
        ),
        migrations.AddField(
            model_name='answer',
            name='ball',
            field=models.IntegerField(default=0),
        ),
    ]
