# Generated by Django 3.2.7 on 2021-09-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessons_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='questions',
        ),
    ]
