# Generated by Django 3.2.7 on 2021-09-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_question_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='questions',
        ),
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.question'),
            preserve_default=False,
        ),
    ]
