# Generated by Django 3.2.7 on 2021-10-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210927_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['id']},
        ),
    ]
