# Generated by Django 3.2.7 on 2021-10-09 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20211008_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='static/course_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='courses.teachers'),
        ),
    ]
