# Generated by Django 3.2.7 on 2021-10-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20211009_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='k',
            field=models.IntegerField(default=0),
        ),
    ]
