# Generated by Django 3.2.7 on 2021-10-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20211013_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerlearns',
            name='course_reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_reader', to='courses.course'),
        ),
        migrations.AddField(
            model_name='requirementsfromreader',
            name='course_requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_requirements', to='courses.course'),
        ),
    ]
